# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created: Fri Aug 14 19:12:55 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(300, 541)
        Form.setMinimumSize(QtCore.QSize(300, 541))
        Form.setMaximumSize(QtCore.QSize(300, 541))
        self.formLayout_2 = QtGui.QFormLayout(Form)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.groupBox_basicInfo = QtGui.QGroupBox(Form)
        self.groupBox_basicInfo.setObjectName(_fromUtf8("groupBox_basicInfo"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_basicInfo)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.contactID_lineEdit = QtGui.QLineEdit(self.groupBox_basicInfo)
        self.contactID_lineEdit.setEnabled(False)
        self.contactID_lineEdit.setObjectName(_fromUtf8("contactID_lineEdit"))
        self.gridLayout.addWidget(self.contactID_lineEdit, 1, 2, 1, 1)
        self.contactType_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.contactType_label.setObjectName(_fromUtf8("contactType_label"))
        self.gridLayout.addWidget(self.contactType_label, 2, 0, 1, 1)
        self.name_lineEdit = QtGui.QLineEdit(self.groupBox_basicInfo)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.gridLayout.addWidget(self.name_lineEdit, 0, 2, 1, 1)
        self.name_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.contactTypecomboBox = QtGui.QComboBox(self.groupBox_basicInfo)
        self.contactTypecomboBox.setObjectName(_fromUtf8("contactTypecomboBox"))
        self.contactTypecomboBox.addItem(_fromUtf8(""))
        self.contactTypecomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.contactTypecomboBox, 2, 2, 1, 1)
        self.contactID_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.contactID_label.setObjectName(_fromUtf8("contactID_label"))
        self.gridLayout.addWidget(self.contactID_label, 1, 0, 1, 1)
        self.contactModelType_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.contactModelType_label.setObjectName(_fromUtf8("contactModelType_label"))
        self.gridLayout.addWidget(self.contactModelType_label, 3, 0, 1, 1)
        self.frictionModelType_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.frictionModelType_label.setObjectName(_fromUtf8("frictionModelType_label"))
        self.gridLayout.addWidget(self.frictionModelType_label, 4, 0, 1, 1)
        self.contactModelTypecomboBox = QtGui.QComboBox(self.groupBox_basicInfo)
        self.contactModelTypecomboBox.setObjectName(_fromUtf8("contactModelTypecomboBox"))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.contactModelTypecomboBox, 3, 2, 1, 1)
        self.frictionModelTypecomboBox = QtGui.QComboBox(self.groupBox_basicInfo)
        self.frictionModelTypecomboBox.setObjectName(_fromUtf8("frictionModelTypecomboBox"))
        self.frictionModelTypecomboBox.addItem(_fromUtf8(""))
        self.frictionModelTypecomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.frictionModelTypecomboBox, 4, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupBox_basicInfo)
        self.bottom_horizontalLayout = QtGui.QHBoxLayout()
        self.bottom_horizontalLayout.setObjectName(_fromUtf8("bottom_horizontalLayout"))
        self.info_lineEdit = QtGui.QLineEdit(Form)
        self.info_lineEdit.setEnabled(False)
        self.info_lineEdit.setObjectName(_fromUtf8("info_lineEdit"))
        self.bottom_horizontalLayout.addWidget(self.info_lineEdit)
        self.save_pushButton = QtGui.QPushButton(Form)
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.save_pushButton)
        self.cancel_pushButton = QtGui.QPushButton(Form)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.cancel_pushButton)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.SpanningRole, self.bottom_horizontalLayout)
        self.groupBox_simulationParameters = QtGui.QGroupBox(Form)
        self.groupBox_simulationParameters.setObjectName(_fromUtf8("groupBox_simulationParameters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_simulationParameters)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Ri_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.Ri_lineEdit.setObjectName(_fromUtf8("Ri_lineEdit"))
        self.gridLayout_2.addWidget(self.Ri_lineEdit, 9, 2, 1, 1)
        self.uPj_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.uPj_label.setObjectName(_fromUtf8("uPj_label"))
        self.gridLayout_2.addWidget(self.uPj_label, 7, 0, 1, 1)
        self.bodyIDj_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.bodyIDj_label.setObjectName(_fromUtf8("bodyIDj_label"))
        self.gridLayout_2.addWidget(self.bodyIDj_label, 1, 0, 1, 1)
        self.bodyIDi_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.bodyIDi_lineEdit.setObjectName(_fromUtf8("bodyIDi_lineEdit"))
        self.gridLayout_2.addWidget(self.bodyIDi_lineEdit, 0, 2, 1, 1)
        self.uPi_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.uPi_label.setObjectName(_fromUtf8("uPi_label"))
        self.gridLayout_2.addWidget(self.uPi_label, 6, 0, 1, 1)
        self.bodyIDi_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.bodyIDi_label.setObjectName(_fromUtf8("bodyIDi_label"))
        self.gridLayout_2.addWidget(self.bodyIDi_label, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_simulationParameters)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 3)
        self.Rj_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.Rj_label.setObjectName(_fromUtf8("Rj_label"))
        self.gridLayout_2.addWidget(self.Rj_label, 10, 0, 1, 1)
        self.uPj_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.uPj_lineEdit.setObjectName(_fromUtf8("uPj_lineEdit"))
        self.gridLayout_2.addWidget(self.uPj_lineEdit, 7, 2, 1, 1)
        self.uPi_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.uPi_lineEdit.setObjectName(_fromUtf8("uPi_lineEdit"))
        self.gridLayout_2.addWidget(self.uPi_lineEdit, 6, 2, 1, 1)
        self.Ri_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.Ri_label.setObjectName(_fromUtf8("Ri_label"))
        self.gridLayout_2.addWidget(self.Ri_label, 9, 0, 1, 1)
        self.Rj_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.Rj_lineEdit.setObjectName(_fromUtf8("Rj_lineEdit"))
        self.gridLayout_2.addWidget(self.Rj_lineEdit, 10, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_simulationParameters)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 8, 0, 1, 3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frictionCoefStatic_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.frictionCoefStatic_label.setObjectName(_fromUtf8("frictionCoefStatic_label"))
        self.gridLayout_4.addWidget(self.frictionCoefStatic_label, 0, 0, 1, 1)
        self.frictionCoefDynamic_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.frictionCoefDynamic_lineEdit.setObjectName(_fromUtf8("frictionCoefDynamic_lineEdit"))
        self.gridLayout_4.addWidget(self.frictionCoefDynamic_lineEdit, 1, 2, 1, 1)
        self.frictionCoefStatic_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.frictionCoefStatic_lineEdit.setObjectName(_fromUtf8("frictionCoefStatic_lineEdit"))
        self.gridLayout_4.addWidget(self.frictionCoefStatic_lineEdit, 0, 2, 1, 1)
        self.restitutionCoef_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.restitutionCoef_lineEdit.setObjectName(_fromUtf8("restitutionCoef_lineEdit"))
        self.gridLayout_4.addWidget(self.restitutionCoef_lineEdit, 2, 2, 1, 1)
        self.frictionCoefDynamic_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.frictionCoefDynamic_label.setObjectName(_fromUtf8("frictionCoefDynamic_label"))
        self.gridLayout_4.addWidget(self.frictionCoefDynamic_label, 1, 0, 1, 1)
        self.restitutionCoef_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.restitutionCoef_label.setObjectName(_fromUtf8("restitutionCoef_label"))
        self.gridLayout_4.addWidget(self.restitutionCoef_label, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 4, 0, 1, 3)
        self.line_3 = QtGui.QFrame(self.groupBox_simulationParameters)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 3, 0, 1, 3)
        self.bodyIDj_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.bodyIDj_lineEdit.setObjectName(_fromUtf8("bodyIDj_lineEdit"))
        self.gridLayout_2.addWidget(self.bodyIDj_lineEdit, 1, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 1, 1, 1)
        self.z_dim_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.z_dim_label.setObjectName(_fromUtf8("z_dim_label"))
        self.gridLayout_2.addWidget(self.z_dim_label, 12, 0, 1, 1)
        self.z_dim_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.z_dim_lineEdit.setObjectName(_fromUtf8("z_dim_lineEdit"))
        self.gridLayout_2.addWidget(self.z_dim_lineEdit, 12, 2, 1, 1)
        self.line_7 = QtGui.QFrame(self.groupBox_simulationParameters)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_2.addWidget(self.line_7, 11, 0, 1, 3)
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.groupBox_simulationParameters)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.name_lineEdit, self.contactID_lineEdit)
        Form.setTabOrder(self.contactID_lineEdit, self.contactTypecomboBox)
        Form.setTabOrder(self.contactTypecomboBox, self.contactModelTypecomboBox)
        Form.setTabOrder(self.contactModelTypecomboBox, self.frictionModelTypecomboBox)
        Form.setTabOrder(self.frictionModelTypecomboBox, self.bodyIDi_lineEdit)
        Form.setTabOrder(self.bodyIDi_lineEdit, self.bodyIDj_lineEdit)
        Form.setTabOrder(self.bodyIDj_lineEdit, self.frictionCoefStatic_lineEdit)
        Form.setTabOrder(self.frictionCoefStatic_lineEdit, self.frictionCoefDynamic_lineEdit)
        Form.setTabOrder(self.frictionCoefDynamic_lineEdit, self.restitutionCoef_lineEdit)
        Form.setTabOrder(self.restitutionCoef_lineEdit, self.uPi_lineEdit)
        Form.setTabOrder(self.uPi_lineEdit, self.uPj_lineEdit)
        Form.setTabOrder(self.uPj_lineEdit, self.Ri_lineEdit)
        Form.setTabOrder(self.Ri_lineEdit, self.Rj_lineEdit)
        Form.setTabOrder(self.Rj_lineEdit, self.info_lineEdit)
        Form.setTabOrder(self.info_lineEdit, self.save_pushButton)
        Form.setTabOrder(self.save_pushButton, self.cancel_pushButton)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Contact", None))
        self.groupBox_basicInfo.setTitle(_translate("Form", "Basic Info", None))
        self.contactType_label.setText(_translate("Form", "Type", None))
        self.name_label.setText(_translate("Form", "Name", None))
        self.contactTypecomboBox.setItemText(0, _translate("Form", "General", None))
        self.contactTypecomboBox.setItemText(1, _translate("Form", "Revolute Clearance Joint", None))
        self.contactID_label.setText(_translate("Form", "Contact id", None))
        self.contactModelType_label.setText(_translate("Form", "Contact Model", None))
        self.frictionModelType_label.setText(_translate("Form", "Friction Model", None))
        self.contactModelTypecomboBox.setItemText(0, _translate("Form", "Hertz", None))
        self.contactModelTypecomboBox.setItemText(1, _translate("Form", "Kelvin-Voigt", None))
        self.contactModelTypecomboBox.setItemText(2, _translate("Form", "Lankarani-Nikravesh", None))
        self.frictionModelTypecomboBox.setItemText(0, _translate("Form", "Coulomb", None))
        self.frictionModelTypecomboBox.setItemText(1, _translate("Form", "Ideal (no friction)", None))
        self.save_pushButton.setText(_translate("Form", "Save", None))
        self.cancel_pushButton.setText(_translate("Form", "Cancel", None))
        self.groupBox_simulationParameters.setTitle(_translate("Form", "Simulation Parameters", None))
        self.uPj_label.setText(_translate("Form", "u_P j, [x, y]", None))
        self.bodyIDj_label.setText(_translate("Form", "Body ID j", None))
        self.uPi_label.setText(_translate("Form", "u_P i, [x, y]", None))
        self.bodyIDi_label.setText(_translate("Form", "Body ID i", None))
        self.Rj_label.setText(_translate("Form", "R j, m", None))
        self.Ri_label.setText(_translate("Form", "R i, m", None))
        self.frictionCoefStatic_label.setText(_translate("Form", "Friction coef. static", None))
        self.frictionCoefDynamic_label.setText(_translate("Form", "Friction coef. dynamic", None))
        self.restitutionCoef_label.setText(_translate("Form", "Restitution coef.", None))
        self.z_dim_label.setText(_translate("Form", "Z coord. pos.,  m", None))

