# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(800, 658)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 658))
        Form.setMaximumSize(QtCore.QSize(800, 659))
        self.gridLayout_7 = QtGui.QGridLayout(Form)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_basicInfo = QtGui.QGroupBox(Form)
        self.groupBox_basicInfo.setObjectName(_fromUtf8("groupBox_basicInfo"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_basicInfo)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.name_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.contactModelType_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.contactModelType_label.setObjectName(_fromUtf8("contactModelType_label"))
        self.gridLayout.addWidget(self.contactModelType_label, 3, 0, 1, 1)
        self.contactModelTypecomboBox = QtGui.QComboBox(self.groupBox_basicInfo)
        self.contactModelTypecomboBox.setMouseTracking(True)
        self.contactModelTypecomboBox.setObjectName(_fromUtf8("contactModelTypecomboBox"))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.contactModelTypecomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.contactModelTypecomboBox, 3, 2, 1, 1)
        self.frictionModelTypecomboBox = QtGui.QComboBox(self.groupBox_basicInfo)
        self.frictionModelTypecomboBox.setMouseTracking(True)
        self.frictionModelTypecomboBox.setObjectName(_fromUtf8("frictionModelTypecomboBox"))
        self.frictionModelTypecomboBox.addItem(_fromUtf8(""))
        self.frictionModelTypecomboBox.addItem(_fromUtf8(""))
        self.frictionModelTypecomboBox.addItem(_fromUtf8(""))
        self.frictionModelTypecomboBox.addItem(_fromUtf8(""))
        self.frictionModelTypecomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.frictionModelTypecomboBox, 4, 2, 1, 1)
        self.frictionModelType_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.frictionModelType_label.setObjectName(_fromUtf8("frictionModelType_label"))
        self.gridLayout.addWidget(self.frictionModelType_label, 4, 0, 1, 1)
        self.contactID_lineEdit = QtGui.QLineEdit(self.groupBox_basicInfo)
        self.contactID_lineEdit.setEnabled(False)
        self.contactID_lineEdit.setObjectName(_fromUtf8("contactID_lineEdit"))
        self.gridLayout.addWidget(self.contactID_lineEdit, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.contactID_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.contactID_label.setObjectName(_fromUtf8("contactID_label"))
        self.gridLayout.addWidget(self.contactID_label, 1, 0, 1, 1)
        self.contactType_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.contactType_label.setObjectName(_fromUtf8("contactType_label"))
        self.gridLayout.addWidget(self.contactType_label, 2, 0, 1, 1)
        self.name_lineEdit = QtGui.QLineEdit(self.groupBox_basicInfo)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.gridLayout.addWidget(self.name_lineEdit, 0, 2, 1, 1)
        self.contactTypecomboBox = QtGui.QComboBox(self.groupBox_basicInfo)
        self.contactTypecomboBox.setObjectName(_fromUtf8("contactTypecomboBox"))
        self.contactTypecomboBox.addItem(_fromUtf8(""))
        self.contactTypecomboBox.addItem(_fromUtf8(""))
        self.contactTypecomboBox.addItem(_fromUtf8(""))
        self.contactTypecomboBox.addItem(_fromUtf8(""))
        self.contactTypecomboBox.addItem(_fromUtf8(""))
        self.contactTypecomboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.contactTypecomboBox, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_basicInfo)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSimParams = QtGui.QWidget()
        self.tabSimParams.setObjectName(_fromUtf8("tabSimParams"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabSimParams)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 3, 0, 1, 1)
        self.visualization = QtGui.QGroupBox(self.tabSimParams)
        self.visualization.setObjectName(_fromUtf8("visualization"))
        self.gridLayout_12 = QtGui.QGridLayout(self.visualization)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.color_label = QtGui.QLabel(self.visualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_label.sizePolicy().hasHeightForWidth())
        self.color_label.setSizePolicy(sizePolicy)
        self.color_label.setMinimumSize(QtCore.QSize(100, 0))
        self.color_label.setObjectName(_fromUtf8("color_label"))
        self.gridLayout_12.addWidget(self.color_label, 0, 1, 1, 1)
        self.color_lineEdit = QtGui.QLineEdit(self.visualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_lineEdit.sizePolicy().hasHeightForWidth())
        self.color_lineEdit.setSizePolicy(sizePolicy)
        self.color_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.color_lineEdit.setObjectName(_fromUtf8("color_lineEdit"))
        self.gridLayout_12.addWidget(self.color_lineEdit, 0, 2, 1, 1)
        self.scale_factor_label = QtGui.QLabel(self.visualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_factor_label.sizePolicy().hasHeightForWidth())
        self.scale_factor_label.setSizePolicy(sizePolicy)
        self.scale_factor_label.setMinimumSize(QtCore.QSize(100, 0))
        self.scale_factor_label.setObjectName(_fromUtf8("scale_factor_label"))
        self.gridLayout_12.addWidget(self.scale_factor_label, 1, 1, 1, 1)
        self.scale_factor_lineEdit = QtGui.QLineEdit(self.visualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_factor_lineEdit.sizePolicy().hasHeightForWidth())
        self.scale_factor_lineEdit.setSizePolicy(sizePolicy)
        self.scale_factor_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.scale_factor_lineEdit.setObjectName(_fromUtf8("scale_factor_lineEdit"))
        self.gridLayout_12.addWidget(self.scale_factor_lineEdit, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridLayout_9.addWidget(self.visualization, 2, 0, 1, 1)
        self.showFn = QtGui.QGroupBox(self.tabSimParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showFn.sizePolicy().hasHeightForWidth())
        self.showFn.setSizePolicy(sizePolicy)
        self.showFn.setMinimumSize(QtCore.QSize(150, 0))
        self.showFn.setObjectName(_fromUtf8("showFn"))
        self.gridLayout_16 = QtGui.QGridLayout(self.showFn)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.Fn_j_checkBox = QtGui.QCheckBox(self.showFn)
        self.Fn_j_checkBox.setObjectName(_fromUtf8("Fn_j_checkBox"))
        self.gridLayout_16.addWidget(self.Fn_j_checkBox, 1, 0, 1, 1)
        self.Fn_i_checkBox = QtGui.QCheckBox(self.showFn)
        self.Fn_i_checkBox.setMinimumSize(QtCore.QSize(100, 0))
        self.Fn_i_checkBox.setObjectName(_fromUtf8("Fn_i_checkBox"))
        self.gridLayout_16.addWidget(self.Fn_i_checkBox, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.showFn, 2, 1, 1, 2)
        self.showFt = QtGui.QGroupBox(self.tabSimParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showFt.sizePolicy().hasHeightForWidth())
        self.showFt.setSizePolicy(sizePolicy)
        self.showFt.setMinimumSize(QtCore.QSize(150, 0))
        self.showFt.setObjectName(_fromUtf8("showFt"))
        self.gridLayout_18 = QtGui.QGridLayout(self.showFt)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.Ft_i_checkBox = QtGui.QCheckBox(self.showFt)
        self.Ft_i_checkBox.setObjectName(_fromUtf8("Ft_i_checkBox"))
        self.gridLayout_18.addWidget(self.Ft_i_checkBox, 0, 0, 1, 1)
        self.Ft_j_checkBox = QtGui.QCheckBox(self.showFt)
        self.Ft_j_checkBox.setObjectName(_fromUtf8("Ft_j_checkBox"))
        self.gridLayout_18.addWidget(self.Ft_j_checkBox, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.showFt, 2, 3, 1, 1)
        self.OthersSimParams = QtGui.QGroupBox(self.tabSimParams)
        self.OthersSimParams.setObjectName(_fromUtf8("OthersSimParams"))
        self.gridLayout_14 = QtGui.QGridLayout(self.OthersSimParams)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem3, 0, 4, 1, 1)
        self.TOL_distance_label = QtGui.QLabel(self.OthersSimParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TOL_distance_label.sizePolicy().hasHeightForWidth())
        self.TOL_distance_label.setSizePolicy(sizePolicy)
        self.TOL_distance_label.setMinimumSize(QtCore.QSize(100, 0))
        self.TOL_distance_label.setObjectName(_fromUtf8("TOL_distance_label"))
        self.gridLayout_14.addWidget(self.TOL_distance_label, 0, 1, 1, 1)
        self.TOL_distance_lineEdit = QtGui.QLineEdit(self.OthersSimParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TOL_distance_lineEdit.sizePolicy().hasHeightForWidth())
        self.TOL_distance_lineEdit.setSizePolicy(sizePolicy)
        self.TOL_distance_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.TOL_distance_lineEdit.setObjectName(_fromUtf8("TOL_distance_lineEdit"))
        self.gridLayout_14.addWidget(self.TOL_distance_lineEdit, 0, 2, 1, 1)
        self.line_3 = QtGui.QFrame(self.OthersSimParams)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_14.addWidget(self.line_3, 0, 3, 1, 1)
        self.gridLayout_9.addWidget(self.OthersSimParams, 1, 0, 1, 4)
        self.MainPropsSimParams = QtGui.QGroupBox(self.tabSimParams)
        self.MainPropsSimParams.setObjectName(_fromUtf8("MainPropsSimParams"))
        self.gridLayout_11 = QtGui.QGridLayout(self.MainPropsSimParams)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.bodyIDj_lineEdit = QtGui.QLineEdit(self.MainPropsSimParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyIDj_lineEdit.sizePolicy().hasHeightForWidth())
        self.bodyIDj_lineEdit.setSizePolicy(sizePolicy)
        self.bodyIDj_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.bodyIDj_lineEdit.setObjectName(_fromUtf8("bodyIDj_lineEdit"))
        self.gridLayout_11.addWidget(self.bodyIDj_lineEdit, 1, 1, 1, 1)
        self.bodyIDj_label = QtGui.QLabel(self.MainPropsSimParams)
        self.bodyIDj_label.setObjectName(_fromUtf8("bodyIDj_label"))
        self.gridLayout_11.addWidget(self.bodyIDj_label, 1, 0, 1, 1)
        self.bodyIDi_lineEdit = QtGui.QLineEdit(self.MainPropsSimParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyIDi_lineEdit.sizePolicy().hasHeightForWidth())
        self.bodyIDi_lineEdit.setSizePolicy(sizePolicy)
        self.bodyIDi_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.bodyIDi_lineEdit.setObjectName(_fromUtf8("bodyIDi_lineEdit"))
        self.gridLayout_11.addWidget(self.bodyIDi_lineEdit, 0, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.MainPropsSimParams)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_11.addWidget(self.line_4, 0, 2, 2, 1)
        self.bodyIDi_label = QtGui.QLabel(self.MainPropsSimParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyIDi_label.sizePolicy().hasHeightForWidth())
        self.bodyIDi_label.setSizePolicy(sizePolicy)
        self.bodyIDi_label.setMinimumSize(QtCore.QSize(100, 0))
        self.bodyIDi_label.setObjectName(_fromUtf8("bodyIDi_label"))
        self.gridLayout_11.addWidget(self.bodyIDi_label, 0, 0, 1, 1)
        self.saveDataToFile_comboBox = QtGui.QComboBox(self.MainPropsSimParams)
        self.saveDataToFile_comboBox.setObjectName(_fromUtf8("saveDataToFile_comboBox"))
        self.saveDataToFile_comboBox.addItem(_fromUtf8(""))
        self.saveDataToFile_comboBox.addItem(_fromUtf8(""))
        self.saveDataToFile_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.saveDataToFile_comboBox, 0, 5, 1, 1)
        self.saveOptions_label = QtGui.QLabel(self.MainPropsSimParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveOptions_label.sizePolicy().hasHeightForWidth())
        self.saveOptions_label.setSizePolicy(sizePolicy)
        self.saveOptions_label.setMinimumSize(QtCore.QSize(100, 0))
        self.saveOptions_label.setObjectName(_fromUtf8("saveOptions_label"))
        self.gridLayout_11.addWidget(self.saveOptions_label, 0, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem4, 1, 5, 1, 1)
        self.gridLayout_9.addWidget(self.MainPropsSimParams, 0, 0, 1, 4)
        self.tabWidget.addTab(self.tabSimParams, _fromUtf8(""))
        self.tabAddParams = QtGui.QWidget()
        self.tabAddParams.setObjectName(_fromUtf8("tabAddParams"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabAddParams)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 0, 1, 1)
        self.RevoluteClearanceJointAddParams = QtGui.QGroupBox(self.tabAddParams)
        self.RevoluteClearanceJointAddParams.setMinimumSize(QtCore.QSize(100, 0))
        self.RevoluteClearanceJointAddParams.setObjectName(_fromUtf8("RevoluteClearanceJointAddParams"))
        self.gridLayout_10 = QtGui.QGridLayout(self.RevoluteClearanceJointAddParams)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.Rj_label = QtGui.QLabel(self.RevoluteClearanceJointAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rj_label.sizePolicy().hasHeightForWidth())
        self.Rj_label.setSizePolicy(sizePolicy)
        self.Rj_label.setObjectName(_fromUtf8("Rj_label"))
        self.gridLayout_10.addWidget(self.Rj_label, 2, 5, 1, 1)
        self.Rj_lineEdit = QtGui.QLineEdit(self.RevoluteClearanceJointAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rj_lineEdit.sizePolicy().hasHeightForWidth())
        self.Rj_lineEdit.setSizePolicy(sizePolicy)
        self.Rj_lineEdit.setObjectName(_fromUtf8("Rj_lineEdit"))
        self.gridLayout_10.addWidget(self.Rj_lineEdit, 2, 6, 1, 1)
        self.Ri_lineEdit = QtGui.QLineEdit(self.RevoluteClearanceJointAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ri_lineEdit.sizePolicy().hasHeightForWidth())
        self.Ri_lineEdit.setSizePolicy(sizePolicy)
        self.Ri_lineEdit.setObjectName(_fromUtf8("Ri_lineEdit"))
        self.gridLayout_10.addWidget(self.Ri_lineEdit, 0, 6, 1, 1)
        self.Ri_label = QtGui.QLabel(self.RevoluteClearanceJointAddParams)
        self.Ri_label.setMinimumSize(QtCore.QSize(100, 0))
        self.Ri_label.setObjectName(_fromUtf8("Ri_label"))
        self.gridLayout_10.addWidget(self.Ri_label, 0, 5, 1, 1)
        self.uPi_lineEdit = QtGui.QLineEdit(self.RevoluteClearanceJointAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uPi_lineEdit.sizePolicy().hasHeightForWidth())
        self.uPi_lineEdit.setSizePolicy(sizePolicy)
        self.uPi_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.uPi_lineEdit.setObjectName(_fromUtf8("uPi_lineEdit"))
        self.gridLayout_10.addWidget(self.uPi_lineEdit, 0, 2, 2, 1)
        self.uPj_label = QtGui.QLabel(self.RevoluteClearanceJointAddParams)
        self.uPj_label.setObjectName(_fromUtf8("uPj_label"))
        self.gridLayout_10.addWidget(self.uPj_label, 2, 0, 1, 1)
        self.uPj_lineEdit = QtGui.QLineEdit(self.RevoluteClearanceJointAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uPj_lineEdit.sizePolicy().hasHeightForWidth())
        self.uPj_lineEdit.setSizePolicy(sizePolicy)
        self.uPj_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.uPj_lineEdit.setObjectName(_fromUtf8("uPj_lineEdit"))
        self.gridLayout_10.addWidget(self.uPj_lineEdit, 2, 2, 1, 1)
        self.uPi_label = QtGui.QLabel(self.RevoluteClearanceJointAddParams)
        self.uPi_label.setMinimumSize(QtCore.QSize(100, 0))
        self.uPi_label.setObjectName(_fromUtf8("uPi_label"))
        self.gridLayout_10.addWidget(self.uPi_label, 0, 0, 2, 2)
        self.line = QtGui.QFrame(self.RevoluteClearanceJointAddParams)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_10.addWidget(self.line, 0, 4, 3, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 0, 7, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.RevoluteClearanceJointAddParams, 2, 0, 1, 2)
        self.GeneralContactAddParams = QtGui.QGroupBox(self.tabAddParams)
        self.GeneralContactAddParams.setEnabled(True)
        self.GeneralContactAddParams.setObjectName(_fromUtf8("GeneralContactAddParams"))
        self.gridLayout_4 = QtGui.QGridLayout(self.GeneralContactAddParams)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.z_dim_label = QtGui.QLabel(self.GeneralContactAddParams)
        self.z_dim_label.setMinimumSize(QtCore.QSize(100, 0))
        self.z_dim_label.setObjectName(_fromUtf8("z_dim_label"))
        self.gridLayout_4.addWidget(self.z_dim_label, 0, 0, 1, 1)
        self.skin_thickness_i_label = QtGui.QLabel(self.GeneralContactAddParams)
        self.skin_thickness_i_label.setMinimumSize(QtCore.QSize(100, 0))
        self.skin_thickness_i_label.setObjectName(_fromUtf8("skin_thickness_i_label"))
        self.gridLayout_4.addWidget(self.skin_thickness_i_label, 1, 0, 1, 1)
        self.skin_thickness_j_lineEdit = QtGui.QLineEdit(self.GeneralContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skin_thickness_j_lineEdit.sizePolicy().hasHeightForWidth())
        self.skin_thickness_j_lineEdit.setSizePolicy(sizePolicy)
        self.skin_thickness_j_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.skin_thickness_j_lineEdit.setObjectName(_fromUtf8("skin_thickness_j_lineEdit"))
        self.gridLayout_4.addWidget(self.skin_thickness_j_lineEdit, 2, 1, 1, 1)
        self.skin_thickness_i_lineEdit = QtGui.QLineEdit(self.GeneralContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skin_thickness_i_lineEdit.sizePolicy().hasHeightForWidth())
        self.skin_thickness_i_lineEdit.setSizePolicy(sizePolicy)
        self.skin_thickness_i_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.skin_thickness_i_lineEdit.setObjectName(_fromUtf8("skin_thickness_i_lineEdit"))
        self.gridLayout_4.addWidget(self.skin_thickness_i_lineEdit, 1, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self.GeneralContactAddParams)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_4.addWidget(self.line_5, 0, 2, 3, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 3, 1, 1)
        self.z_dim_lineEdit = QtGui.QLineEdit(self.GeneralContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_dim_lineEdit.sizePolicy().hasHeightForWidth())
        self.z_dim_lineEdit.setSizePolicy(sizePolicy)
        self.z_dim_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.z_dim_lineEdit.setObjectName(_fromUtf8("z_dim_lineEdit"))
        self.gridLayout_4.addWidget(self.z_dim_lineEdit, 0, 1, 1, 1)
        self.skin_thickness_j_label = QtGui.QLabel(self.GeneralContactAddParams)
        self.skin_thickness_j_label.setMinimumSize(QtCore.QSize(100, 0))
        self.skin_thickness_j_label.setObjectName(_fromUtf8("skin_thickness_j_label"))
        self.gridLayout_4.addWidget(self.skin_thickness_j_label, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.GeneralContactAddParams, 0, 0, 1, 2)
        self.SphereSphereContactAddParams = QtGui.QGroupBox(self.tabAddParams)
        self.SphereSphereContactAddParams.setObjectName(_fromUtf8("SphereSphereContactAddParams"))
        self.gridLayout_13 = QtGui.QGridLayout(self.SphereSphereContactAddParams)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.R0j_label = QtGui.QLabel(self.SphereSphereContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R0j_label.sizePolicy().hasHeightForWidth())
        self.R0j_label.setSizePolicy(sizePolicy)
        self.R0j_label.setMinimumSize(QtCore.QSize(100, 0))
        self.R0j_label.setObjectName(_fromUtf8("R0j_label"))
        self.gridLayout_13.addWidget(self.R0j_label, 1, 0, 1, 1)
        self.R0i_label = QtGui.QLabel(self.SphereSphereContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R0i_label.sizePolicy().hasHeightForWidth())
        self.R0i_label.setSizePolicy(sizePolicy)
        self.R0i_label.setMinimumSize(QtCore.QSize(100, 0))
        self.R0i_label.setObjectName(_fromUtf8("R0i_label"))
        self.gridLayout_13.addWidget(self.R0i_label, 0, 0, 1, 1)
        self.R0i_lineEdit = QtGui.QLineEdit(self.SphereSphereContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R0i_lineEdit.sizePolicy().hasHeightForWidth())
        self.R0i_lineEdit.setSizePolicy(sizePolicy)
        self.R0i_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.R0i_lineEdit.setObjectName(_fromUtf8("R0i_lineEdit"))
        self.gridLayout_13.addWidget(self.R0i_lineEdit, 0, 1, 1, 1)
        self.R0j_lineEdit = QtGui.QLineEdit(self.SphereSphereContactAddParams)
        self.R0j_lineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R0j_lineEdit.sizePolicy().hasHeightForWidth())
        self.R0j_lineEdit.setSizePolicy(sizePolicy)
        self.R0j_lineEdit.setObjectName(_fromUtf8("R0j_lineEdit"))
        self.gridLayout_13.addWidget(self.R0j_lineEdit, 1, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem9, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.SphereSphereContactAddParams, 3, 0, 1, 1)
        self.PlaneSphereContactAddParams = QtGui.QGroupBox(self.tabAddParams)
        self.PlaneSphereContactAddParams.setObjectName(_fromUtf8("PlaneSphereContactAddParams"))
        self.gridLayout_19 = QtGui.QGridLayout(self.PlaneSphereContactAddParams)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.R0j_sphere_lineEdit = QtGui.QLineEdit(self.PlaneSphereContactAddParams)
        self.R0j_sphere_lineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R0j_sphere_lineEdit.sizePolicy().hasHeightForWidth())
        self.R0j_sphere_lineEdit.setSizePolicy(sizePolicy)
        self.R0j_sphere_lineEdit.setObjectName(_fromUtf8("R0j_sphere_lineEdit"))
        self.gridLayout_19.addWidget(self.R0j_sphere_lineEdit, 2, 1, 1, 1)
        self.R0j_sphere_label = QtGui.QLabel(self.PlaneSphereContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R0j_sphere_label.sizePolicy().hasHeightForWidth())
        self.R0j_sphere_label.setSizePolicy(sizePolicy)
        self.R0j_sphere_label.setMinimumSize(QtCore.QSize(100, 0))
        self.R0j_sphere_label.setObjectName(_fromUtf8("R0j_sphere_label"))
        self.gridLayout_19.addWidget(self.R0j_sphere_label, 2, 0, 1, 1)
        self.normal_i_lineEdit = QtGui.QLineEdit(self.PlaneSphereContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normal_i_lineEdit.sizePolicy().hasHeightForWidth())
        self.normal_i_lineEdit.setSizePolicy(sizePolicy)
        self.normal_i_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.normal_i_lineEdit.setObjectName(_fromUtf8("normal_i_lineEdit"))
        self.gridLayout_19.addWidget(self.normal_i_lineEdit, 1, 1, 1, 1)
        self.normal_i_label = QtGui.QLabel(self.PlaneSphereContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normal_i_label.sizePolicy().hasHeightForWidth())
        self.normal_i_label.setSizePolicy(sizePolicy)
        self.normal_i_label.setMinimumSize(QtCore.QSize(100, 0))
        self.normal_i_label.setObjectName(_fromUtf8("normal_i_label"))
        self.gridLayout_19.addWidget(self.normal_i_label, 1, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem10, 1, 2, 1, 1)
        self.uPi_label_2 = QtGui.QLabel(self.PlaneSphereContactAddParams)
        self.uPi_label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.uPi_label_2.setObjectName(_fromUtf8("uPi_label_2"))
        self.gridLayout_19.addWidget(self.uPi_label_2, 0, 0, 1, 1)
        self.uPi_lineEdit_2 = QtGui.QLineEdit(self.PlaneSphereContactAddParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uPi_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.uPi_lineEdit_2.setSizePolicy(sizePolicy)
        self.uPi_lineEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.uPi_lineEdit_2.setObjectName(_fromUtf8("uPi_lineEdit_2"))
        self.gridLayout_19.addWidget(self.uPi_lineEdit_2, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.PlaneSphereContactAddParams, 3, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tabAddParams, _fromUtf8(""))
        self.tabContactModel = QtGui.QWidget()
        self.tabContactModel.setObjectName(_fromUtf8("tabContactModel"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabContactModel)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 4, 0, 1, 1)
        self.ContactModelProperties = QtGui.QGroupBox(self.tabContactModel)
        self.ContactModelProperties.setObjectName(_fromUtf8("ContactModelProperties"))
        self.gridLayout_3 = QtGui.QGridLayout(self.ContactModelProperties)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 0, 3, 1, 1)
        self.restitution_coefficient_lineEdit = QtGui.QLineEdit(self.ContactModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restitution_coefficient_lineEdit.sizePolicy().hasHeightForWidth())
        self.restitution_coefficient_lineEdit.setSizePolicy(sizePolicy)
        self.restitution_coefficient_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.restitution_coefficient_lineEdit.setObjectName(_fromUtf8("restitution_coefficient_lineEdit"))
        self.gridLayout_3.addWidget(self.restitution_coefficient_lineEdit, 0, 1, 1, 1)
        self.contact_stiffness_lineEdit = QtGui.QLineEdit(self.ContactModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contact_stiffness_lineEdit.sizePolicy().hasHeightForWidth())
        self.contact_stiffness_lineEdit.setSizePolicy(sizePolicy)
        self.contact_stiffness_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.contact_stiffness_lineEdit.setObjectName(_fromUtf8("contact_stiffness_lineEdit"))
        self.gridLayout_3.addWidget(self.contact_stiffness_lineEdit, 1, 1, 1, 1)
        self.damping_coefficient_lineEdit = QtGui.QLineEdit(self.ContactModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.damping_coefficient_lineEdit.sizePolicy().hasHeightForWidth())
        self.damping_coefficient_lineEdit.setSizePolicy(sizePolicy)
        self.damping_coefficient_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.damping_coefficient_lineEdit.setObjectName(_fromUtf8("damping_coefficient_lineEdit"))
        self.gridLayout_3.addWidget(self.damping_coefficient_lineEdit, 2, 1, 1, 1)
        self.restitution_coefficient_label = QtGui.QLabel(self.ContactModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restitution_coefficient_label.sizePolicy().hasHeightForWidth())
        self.restitution_coefficient_label.setSizePolicy(sizePolicy)
        self.restitution_coefficient_label.setMinimumSize(QtCore.QSize(100, 0))
        self.restitution_coefficient_label.setObjectName(_fromUtf8("restitution_coefficient_label"))
        self.gridLayout_3.addWidget(self.restitution_coefficient_label, 0, 0, 1, 1)
        self.contact_stiffness_label = QtGui.QLabel(self.ContactModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contact_stiffness_label.sizePolicy().hasHeightForWidth())
        self.contact_stiffness_label.setSizePolicy(sizePolicy)
        self.contact_stiffness_label.setMinimumSize(QtCore.QSize(100, 0))
        self.contact_stiffness_label.setObjectName(_fromUtf8("contact_stiffness_label"))
        self.gridLayout_3.addWidget(self.contact_stiffness_label, 1, 0, 1, 1)
        self.damping_coefficient_label = QtGui.QLabel(self.ContactModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.damping_coefficient_label.sizePolicy().hasHeightForWidth())
        self.damping_coefficient_label.setSizePolicy(sizePolicy)
        self.damping_coefficient_label.setMinimumSize(QtCore.QSize(100, 0))
        self.damping_coefficient_label.setObjectName(_fromUtf8("damping_coefficient_label"))
        self.gridLayout_3.addWidget(self.damping_coefficient_label, 2, 0, 1, 1)
        self.power_exponent_label = QtGui.QLabel(self.ContactModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_exponent_label.sizePolicy().hasHeightForWidth())
        self.power_exponent_label.setSizePolicy(sizePolicy)
        self.power_exponent_label.setMinimumSize(QtCore.QSize(100, 0))
        self.power_exponent_label.setObjectName(_fromUtf8("power_exponent_label"))
        self.gridLayout_3.addWidget(self.power_exponent_label, 3, 0, 1, 1)
        self.power_exponent_lineEdit = QtGui.QLineEdit(self.ContactModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_exponent_lineEdit.sizePolicy().hasHeightForWidth())
        self.power_exponent_lineEdit.setSizePolicy(sizePolicy)
        self.power_exponent_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.power_exponent_lineEdit.setObjectName(_fromUtf8("power_exponent_lineEdit"))
        self.gridLayout_3.addWidget(self.power_exponent_lineEdit, 3, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.ContactModelProperties)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_3.addWidget(self.line_7, 0, 2, 4, 1)
        self.gridLayout_5.addWidget(self.ContactModelProperties, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tabContactModel, _fromUtf8(""))
        self.tabFrictionModel = QtGui.QWidget()
        self.tabFrictionModel.setObjectName(_fromUtf8("tabFrictionModel"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabFrictionModel)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.FrictionModelProperties = QtGui.QGroupBox(self.tabFrictionModel)
        self.FrictionModelProperties.setObjectName(_fromUtf8("FrictionModelProperties"))
        self.gridLayout_15 = QtGui.QGridLayout(self.FrictionModelProperties)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.v0_label = QtGui.QLabel(self.FrictionModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v0_label.sizePolicy().hasHeightForWidth())
        self.v0_label.setSizePolicy(sizePolicy)
        self.v0_label.setMinimumSize(QtCore.QSize(100, 0))
        self.v0_label.setObjectName(_fromUtf8("v0_label"))
        self.gridLayout_15.addWidget(self.v0_label, 2, 0, 1, 1)
        self.frictionCoefDynamic_label = QtGui.QLabel(self.FrictionModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frictionCoefDynamic_label.sizePolicy().hasHeightForWidth())
        self.frictionCoefDynamic_label.setSizePolicy(sizePolicy)
        self.frictionCoefDynamic_label.setMinimumSize(QtCore.QSize(100, 0))
        self.frictionCoefDynamic_label.setObjectName(_fromUtf8("frictionCoefDynamic_label"))
        self.gridLayout_15.addWidget(self.frictionCoefDynamic_label, 0, 0, 1, 1)
        self.vT_lineEdit = QtGui.QLineEdit(self.FrictionModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vT_lineEdit.sizePolicy().hasHeightForWidth())
        self.vT_lineEdit.setSizePolicy(sizePolicy)
        self.vT_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.vT_lineEdit.setObjectName(_fromUtf8("vT_lineEdit"))
        self.gridLayout_15.addWidget(self.vT_lineEdit, 3, 1, 1, 1)
        self.vT_label = QtGui.QLabel(self.FrictionModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vT_label.sizePolicy().hasHeightForWidth())
        self.vT_label.setSizePolicy(sizePolicy)
        self.vT_label.setMinimumSize(QtCore.QSize(100, 0))
        self.vT_label.setObjectName(_fromUtf8("vT_label"))
        self.gridLayout_15.addWidget(self.vT_label, 3, 0, 1, 1)
        self.frictionCoefDynamic_lineEdit = QtGui.QLineEdit(self.FrictionModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frictionCoefDynamic_lineEdit.sizePolicy().hasHeightForWidth())
        self.frictionCoefDynamic_lineEdit.setSizePolicy(sizePolicy)
        self.frictionCoefDynamic_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.frictionCoefDynamic_lineEdit.setObjectName(_fromUtf8("frictionCoefDynamic_lineEdit"))
        self.gridLayout_15.addWidget(self.frictionCoefDynamic_lineEdit, 0, 1, 1, 1)
        self.frictionCoefStatic_lineEdit = QtGui.QLineEdit(self.FrictionModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frictionCoefStatic_lineEdit.sizePolicy().hasHeightForWidth())
        self.frictionCoefStatic_lineEdit.setSizePolicy(sizePolicy)
        self.frictionCoefStatic_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.frictionCoefStatic_lineEdit.setObjectName(_fromUtf8("frictionCoefStatic_lineEdit"))
        self.gridLayout_15.addWidget(self.frictionCoefStatic_lineEdit, 1, 1, 1, 1)
        self.frictionCoefStatic_label = QtGui.QLabel(self.FrictionModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frictionCoefStatic_label.sizePolicy().hasHeightForWidth())
        self.frictionCoefStatic_label.setSizePolicy(sizePolicy)
        self.frictionCoefStatic_label.setMinimumSize(QtCore.QSize(100, 0))
        self.frictionCoefStatic_label.setObjectName(_fromUtf8("frictionCoefStatic_label"))
        self.gridLayout_15.addWidget(self.frictionCoefStatic_label, 1, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem13, 0, 3, 1, 1)
        self.v0_lineEdit = QtGui.QLineEdit(self.FrictionModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v0_lineEdit.sizePolicy().hasHeightForWidth())
        self.v0_lineEdit.setSizePolicy(sizePolicy)
        self.v0_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.v0_lineEdit.setObjectName(_fromUtf8("v0_lineEdit"))
        self.gridLayout_15.addWidget(self.v0_lineEdit, 2, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self.FrictionModelProperties)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_15.addWidget(self.line_8, 0, 2, 4, 1)
        self.gridLayout_6.addWidget(self.FrictionModelProperties, 4, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem14, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabFrictionModel, _fromUtf8(""))
        self.tabBody_i = QtGui.QWidget()
        self.tabBody_i.setObjectName(_fromUtf8("tabBody_i"))
        self.label = QtGui.QLabel(self.tabBody_i)
        self.label.setGeometry(QtCore.QRect(0, 0, 91, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.tabBody_i, _fromUtf8(""))
        self.tabBody_j = QtGui.QWidget()
        self.tabBody_j.setObjectName(_fromUtf8("tabBody_j"))
        self.label_2 = QtGui.QLabel(self.tabBody_j)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 91, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget.addTab(self.tabBody_j, _fromUtf8(""))
        self.tabRoughness = QtGui.QWidget()
        self.tabRoughness.setObjectName(_fromUtf8("tabRoughness"))
        self.label_3 = QtGui.QLabel(self.tabRoughness)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 91, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tabWidget.addTab(self.tabRoughness, _fromUtf8(""))
        self.tabWear = QtGui.QWidget()
        self.tabWear.setObjectName(_fromUtf8("tabWear"))
        self.label_4 = QtGui.QLabel(self.tabWear)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 91, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.tabWear, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.bottom_horizontalLayout = QtGui.QHBoxLayout()
        self.bottom_horizontalLayout.setObjectName(_fromUtf8("bottom_horizontalLayout"))
        self.info_lineEdit = QtGui.QLineEdit(Form)
        self.info_lineEdit.setEnabled(False)
        self.info_lineEdit.setObjectName(_fromUtf8("info_lineEdit"))
        self.bottom_horizontalLayout.addWidget(self.info_lineEdit)
        self.save_pushButton = QtGui.QPushButton(Form)
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.save_pushButton)
        self.cancel_pushButton = QtGui.QPushButton(Form)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.cancel_pushButton)
        self.verticalLayout.addLayout(self.bottom_horizontalLayout)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Contact", None))
        self.groupBox_basicInfo.setTitle(_translate("Form", "Basic Info", None))
        self.name_label.setText(_translate("Form", "Name", None))
        self.contactModelType_label.setText(_translate("Form", "Contact Model", None))
        self.contactModelTypecomboBox.setItemText(0, _translate("Form", "Hertz", None))
        self.contactModelTypecomboBox.setItemText(1, _translate("Form", "Kelvin-Voigt", None))
        self.contactModelTypecomboBox.setItemText(2, _translate("Form", "Lankarani-Nikravesh", None))
        self.contactModelTypecomboBox.setItemText(3, _translate("Form", "Hunt-Crossley", None))
        self.contactModelTypecomboBox.setItemText(4, _translate("Form", "Herbert-McWhannell", None))
        self.contactModelTypecomboBox.setItemText(5, _translate("Form", "Lee-Wang", None))
        self.contactModelTypecomboBox.setItemText(6, _translate("Form", "Flores et al", None))
        self.contactModelTypecomboBox.setItemText(7, _translate("Form", "Zhiying-Qishao", None))
        self.contactModelTypecomboBox.setItemText(8, _translate("Form", "Gonthier et al", None))
        self.contactModelTypecomboBox.setItemText(9, _translate("Form", "Hu-Guo", None))
        self.contactModelTypecomboBox.setItemText(10, _translate("Form", "Dubowsky-Freudenstein", None))
        self.contactModelTypecomboBox.setItemText(11, _translate("Form", "Esdu-78035", None))
        self.frictionModelTypecomboBox.setItemText(0, _translate("Form", "Ideal", None))
        self.frictionModelTypecomboBox.setItemText(1, _translate("Form", "Coulomb", None))
        self.frictionModelTypecomboBox.setItemText(2, _translate("Form", "Stribeck", None))
        self.frictionModelTypecomboBox.setItemText(3, _translate("Form", "Continous zero-velocity crossing", None))
        self.frictionModelTypecomboBox.setItemText(4, _translate("Form", "LeGru", None))
        self.frictionModelType_label.setText(_translate("Form", "Friction Model", None))
        self.contactID_label.setText(_translate("Form", "Contact id", None))
        self.contactType_label.setText(_translate("Form", "Type", None))
        self.contactTypecomboBox.setItemText(0, _translate("Form", "General", None))
        self.contactTypecomboBox.setItemText(1, _translate("Form", "Pin-Slot Clearance Joint (linear)", None))
        self.contactTypecomboBox.setItemText(2, _translate("Form", "Pin-Slot Clearance Joint (angular)", None))
        self.contactTypecomboBox.setItemText(3, _translate("Form", "Revolute Clearance Joint", None))
        self.contactTypecomboBox.setItemText(4, _translate("Form", "Contact Sphere-Sphere", None))
        self.contactTypecomboBox.setItemText(5, _translate("Form", "Contact Plane-Sphere", None))
        self.visualization.setTitle(_translate("Form", "Visualization", None))
        self.color_label.setText(_translate("Form", "Color, RGB", None))
        self.scale_factor_label.setText(_translate("Form", "Scale Factor", None))
        self.showFn.setTitle(_translate("Form", "Show contact force", None))
        self.Fn_j_checkBox.setText(_translate("Form", "Fn Body j", None))
        self.Fn_i_checkBox.setText(_translate("Form", "Fn Body i", None))
        self.showFt.setTitle(_translate("Form", "Show friction force", None))
        self.Ft_i_checkBox.setText(_translate("Form", "Ft Body i", None))
        self.Ft_j_checkBox.setText(_translate("Form", "Ft Body j", None))
        self.OthersSimParams.setTitle(_translate("Form", "Others", None))
        self.TOL_distance_label.setText(_translate("Form", "TOL (distance), m", None))
        self.MainPropsSimParams.setTitle(_translate("Form", "Main Properties", None))
        self.bodyIDj_label.setText(_translate("Form", "Body ID j", None))
        self.bodyIDi_label.setText(_translate("Form", "Body ID i", None))
        self.saveDataToFile_comboBox.setItemText(0, _translate("Form", "Discard", None))
        self.saveDataToFile_comboBox.setItemText(1, _translate("Form", "Overwrite (existing file)", None))
        self.saveDataToFile_comboBox.setItemText(2, _translate("Form", "Save to new (next available) file", None))
        self.saveOptions_label.setText(_translate("Form", "Save options", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSimParams), _translate("Form", "Sim.Params", None))
        self.RevoluteClearanceJointAddParams.setTitle(_translate("Form", "Revolute Clearance Joint", None))
        self.Rj_label.setText(_translate("Form", "R j, m", None))
        self.Ri_label.setText(_translate("Form", "R i, m", None))
        self.uPj_label.setText(_translate("Form", "u_P j, [x, y]", None))
        self.uPi_label.setText(_translate("Form", "u_P i, [x, y]", None))
        self.GeneralContactAddParams.setTitle(_translate("Form", "General Contact", None))
        self.z_dim_label.setText(_translate("Form", "Z coord. pos.,  m", None))
        self.skin_thickness_i_label.setText(_translate("Form", "Skin thickness i, m", None))
        self.skin_thickness_j_label.setText(_translate("Form", "Skin thickness j, m", None))
        self.SphereSphereContactAddParams.setTitle(_translate("Form", "Contact Spehere-Sphere", None))
        self.R0j_label.setText(_translate("Form", "R0 j,  m", None))
        self.R0i_label.setText(_translate("Form", "R0 i,  m", None))
        self.PlaneSphereContactAddParams.setTitle(_translate("Form", "Contact Plane-Sphere", None))
        self.R0j_sphere_label.setText(_translate("Form", "R0 j,  m", None))
        self.normal_i_label.setText(_translate("Form", "normal i", None))
        self.uPi_label_2.setText(_translate("Form", "u_P i, [x, y]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAddParams), _translate("Form", "Add.Params", None))
        self.ContactModelProperties.setTitle(_translate("Form", "Contact Model Properties", None))
        self.restitution_coefficient_label.setText(_translate("Form", "Restitution coef.", None))
        self.contact_stiffness_label.setText(_translate("Form", "Cont. stiffness, N/m", None))
        self.damping_coefficient_label.setText(_translate("Form", "Damp. coef., Ns/m", None))
        self.power_exponent_label.setText(_translate("Form", "n - power exp.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabContactModel), _translate("Form", "Contact model", None))
        self.FrictionModelProperties.setTitle(_translate("Form", "Friction Model Properties", None))
        self.v0_label.setText(_translate("Form", "v,, m/s", None))
        self.frictionCoefDynamic_label.setText(_translate("Form", "Friction coef. dyn.", None))
        self.vT_label.setText(_translate("Form", "vT, m/s", None))
        self.frictionCoefStatic_label.setText(_translate("Form", "Friction coef. stat.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFrictionModel), _translate("Form", "Friction model", None))
        self.label.setText(_translate("Form", "Under construction", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBody_i), _translate("Form", "Body i", None))
        self.label_2.setText(_translate("Form", "Under construction", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBody_j), _translate("Form", "Body j", None))
        self.label_3.setText(_translate("Form", "Under construction", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRoughness), _translate("Form", "Roughness", None))
        self.label_4.setText(_translate("Form", "Under construction", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWear), _translate("Form", "Wear", None))
        self.save_pushButton.setText(_translate("Form", "Save", None))
        self.cancel_pushButton.setText(_translate("Form", "Cancel", None))

