# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'force.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(440, 709)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.loadFromFile_label = QtGui.QLabel(self.groupBox)
        self.loadFromFile_label.setObjectName(_fromUtf8("loadFromFile_label"))
        self.gridLayout.addWidget(self.loadFromFile_label, 2, 0, 1, 1)
        self.forceID_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.forceID_lineEdit.setEnabled(False)
        self.forceID_lineEdit.setObjectName(_fromUtf8("forceID_lineEdit"))
        self.gridLayout.addWidget(self.forceID_lineEdit, 1, 1, 1, 1)
        self.load_data_pushButton = QtGui.QPushButton(self.groupBox)
        self.load_data_pushButton.setObjectName(_fromUtf8("load_data_pushButton"))
        self.gridLayout.addWidget(self.load_data_pushButton, 2, 1, 1, 1)
        self.name_label = QtGui.QLabel(self.groupBox)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.gridLayout.addWidget(self.name_lineEdit, 0, 1, 1, 1)
        self.forceID_label = QtGui.QLabel(self.groupBox)
        self.forceID_label.setObjectName(_fromUtf8("forceID_label"))
        self.gridLayout.addWidget(self.forceID_label, 1, 0, 1, 1)
        self.file_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.file_lineEdit.setObjectName(_fromUtf8("file_lineEdit"))
        self.gridLayout.addWidget(self.file_lineEdit, 3, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.simParams = QtGui.QWidget()
        self.simParams.setObjectName(_fromUtf8("simParams"))
        self.gridLayout_2 = QtGui.QGridLayout(self.simParams)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bodyID_label = QtGui.QLabel(self.simParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyID_label.sizePolicy().hasHeightForWidth())
        self.bodyID_label.setSizePolicy(sizePolicy)
        self.bodyID_label.setMinimumSize(QtCore.QSize(0, 27))
        self.bodyID_label.setObjectName(_fromUtf8("bodyID_label"))
        self.gridLayout_2.addWidget(self.bodyID_label, 0, 0, 1, 1)
        self.Fy_lineEdit = QtGui.QLineEdit(self.simParams)
        self.Fy_lineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.Fy_lineEdit.setInputMask(_fromUtf8(""))
        self.Fy_lineEdit.setObjectName(_fromUtf8("Fy_lineEdit"))
        self.gridLayout_2.addWidget(self.Fy_lineEdit, 3, 1, 1, 1)
        self.Fy_label = QtGui.QLabel(self.simParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fy_label.sizePolicy().hasHeightForWidth())
        self.Fy_label.setSizePolicy(sizePolicy)
        self.Fy_label.setMinimumSize(QtCore.QSize(0, 27))
        self.Fy_label.setObjectName(_fromUtf8("Fy_label"))
        self.gridLayout_2.addWidget(self.Fy_label, 3, 0, 1, 1)
        self.bodyID_lineEdit = QtGui.QLineEdit(self.simParams)
        self.bodyID_lineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.bodyID_lineEdit.setObjectName(_fromUtf8("bodyID_lineEdit"))
        self.gridLayout_2.addWidget(self.bodyID_lineEdit, 0, 1, 1, 1)
        self.Fx_label = QtGui.QLabel(self.simParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fx_label.sizePolicy().hasHeightForWidth())
        self.Fx_label.setSizePolicy(sizePolicy)
        self.Fx_label.setMinimumSize(QtCore.QSize(0, 27))
        self.Fx_label.setObjectName(_fromUtf8("Fx_label"))
        self.gridLayout_2.addWidget(self.Fx_label, 2, 0, 1, 1)
        self.Mz_label = QtGui.QLabel(self.simParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mz_label.sizePolicy().hasHeightForWidth())
        self.Mz_label.setSizePolicy(sizePolicy)
        self.Mz_label.setMinimumSize(QtCore.QSize(0, 27))
        self.Mz_label.setObjectName(_fromUtf8("Mz_label"))
        self.gridLayout_2.addWidget(self.Mz_label, 4, 0, 1, 1)
        self.uPi_label = QtGui.QLabel(self.simParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uPi_label.sizePolicy().hasHeightForWidth())
        self.uPi_label.setSizePolicy(sizePolicy)
        self.uPi_label.setMinimumSize(QtCore.QSize(0, 27))
        self.uPi_label.setObjectName(_fromUtf8("uPi_label"))
        self.gridLayout_2.addWidget(self.uPi_label, 1, 0, 1, 1)
        self.Mz_lineEdit = QtGui.QLineEdit(self.simParams)
        self.Mz_lineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.Mz_lineEdit.setObjectName(_fromUtf8("Mz_lineEdit"))
        self.gridLayout_2.addWidget(self.Mz_lineEdit, 4, 1, 1, 1)
        self.Fx_lineEdit = QtGui.QLineEdit(self.simParams)
        self.Fx_lineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.Fx_lineEdit.setObjectName(_fromUtf8("Fx_lineEdit"))
        self.gridLayout_2.addWidget(self.Fx_lineEdit, 2, 1, 1, 1)
        self.uPi_lineEdit = QtGui.QLineEdit(self.simParams)
        self.uPi_lineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.uPi_lineEdit.setObjectName(_fromUtf8("uPi_lineEdit"))
        self.gridLayout_2.addWidget(self.uPi_lineEdit, 1, 1, 1, 1)
        self.CS_label = QtGui.QLabel(self.simParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CS_label.sizePolicy().hasHeightForWidth())
        self.CS_label.setSizePolicy(sizePolicy)
        self.CS_label.setMinimumSize(QtCore.QSize(0, 27))
        self.CS_label.setObjectName(_fromUtf8("CS_label"))
        self.gridLayout_2.addWidget(self.CS_label, 5, 0, 1, 1)
        self.CS_comboBox = QtGui.QComboBox(self.simParams)
        self.CS_comboBox.setMinimumSize(QtCore.QSize(0, 27))
        self.CS_comboBox.setObjectName(_fromUtf8("CS_comboBox"))
        self.CS_comboBox.addItem(_fromUtf8(""))
        self.CS_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.CS_comboBox, 5, 1, 1, 1)
        self.tabWidget.addTab(self.simParams, _fromUtf8(""))
        self.solution = QtGui.QWidget()
        self.solution.setObjectName(_fromUtf8("solution"))
        self.gridLayout_4 = QtGui.QGridLayout(self.solution)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tableWidget = QtGui.QTableWidget(self.solution)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.solution, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.color_label = QtGui.QLabel(self.groupBox_2)
        self.color_label.setObjectName(_fromUtf8("color_label"))
        self.gridLayout_3.addWidget(self.color_label, 0, 0, 1, 1)
        self.color_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.color_lineEdit.setObjectName(_fromUtf8("color_lineEdit"))
        self.gridLayout_3.addWidget(self.color_lineEdit, 0, 1, 1, 1)
        self.scale_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.scale_lineEdit.setObjectName(_fromUtf8("scale_lineEdit"))
        self.gridLayout_3.addWidget(self.scale_lineEdit, 1, 1, 1, 1)
        self.scale_label = QtGui.QLabel(self.groupBox_2)
        self.scale_label.setObjectName(_fromUtf8("scale_label"))
        self.gridLayout_3.addWidget(self.scale_label, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.bottom_horizontalLayout = QtGui.QHBoxLayout()
        self.bottom_horizontalLayout.setSpacing(6)
        self.bottom_horizontalLayout.setObjectName(_fromUtf8("bottom_horizontalLayout"))
        self.info_lineEdit = QtGui.QLineEdit(Form)
        self.info_lineEdit.setEnabled(False)
        self.info_lineEdit.setObjectName(_fromUtf8("info_lineEdit"))
        self.bottom_horizontalLayout.addWidget(self.info_lineEdit)
        self.save_pushButton = QtGui.QPushButton(Form)
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.save_pushButton)
        self.cancel_pushButton = QtGui.QPushButton(Form)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.cancel_pushButton)
        self.verticalLayout.addLayout(self.bottom_horizontalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Force", None))
        self.groupBox.setTitle(_translate("Form", "Basic Info", None))
        self.loadFromFile_label.setText(_translate("Form", "Load from .dat file", None))
        self.load_data_pushButton.setText(_translate("Form", "Load", None))
        self.name_label.setText(_translate("Form", "Name", None))
        self.forceID_label.setText(_translate("Form", "Force id", None))
        self.bodyID_label.setText(_translate("Form", "Body ID i", None))
        self.Fy_label.setText(_translate("Form", "Fy, N", None))
        self.Fx_label.setText(_translate("Form", "Fx, N", None))
        self.Mz_label.setText(_translate("Form", "Mz, Nm", None))
        self.uPi_label.setText(_translate("Form", "u_P, [x, y]", None))
        self.CS_label.setText(_translate("Form", "CS", None))
        self.CS_comboBox.setItemText(0, _translate("Form", "LCS", None))
        self.CS_comboBox.setItemText(1, _translate("Form", "GCS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simParams), _translate("Form", "Sim.Params", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.solution), _translate("Form", "Solution", None))
        self.groupBox_2.setTitle(_translate("Form", "Visualization", None))
        self.color_label.setText(_translate("Form", "Color, RGB", None))
        self.scale_label.setText(_translate("Form", "Scale GL", None))
        self.save_pushButton.setText(_translate("Form", "Save", None))
        self.cancel_pushButton.setText(_translate("Form", "Cancel", None))

