# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spring.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(300, 642)
        Form.setMinimumSize(QtCore.QSize(300, 642))
        Form.setMaximumSize(QtCore.QSize(302, 642))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_basicInfo = QtGui.QGroupBox(Form)
        self.groupBox_basicInfo.setObjectName(_fromUtf8("groupBox_basicInfo"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_basicInfo)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.springID_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.springID_label.setObjectName(_fromUtf8("springID_label"))
        self.gridLayout.addWidget(self.springID_label, 1, 0, 1, 1)
        self.name_lineEdit = QtGui.QLineEdit(self.groupBox_basicInfo)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.gridLayout.addWidget(self.name_lineEdit, 0, 2, 1, 1)
        self.springType_comboBox = QtGui.QComboBox(self.groupBox_basicInfo)
        self.springType_comboBox.setObjectName(_fromUtf8("springType_comboBox"))
        self.springType_comboBox.addItem(_fromUtf8(""))
        self.springType_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.springType_comboBox, 2, 2, 1, 1)
        self.springType_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.springType_label.setObjectName(_fromUtf8("springType_label"))
        self.gridLayout.addWidget(self.springType_label, 2, 0, 1, 1)
        self.springID_lineEdit = QtGui.QLineEdit(self.groupBox_basicInfo)
        self.springID_lineEdit.setEnabled(False)
        self.springID_lineEdit.setObjectName(_fromUtf8("springID_lineEdit"))
        self.gridLayout.addWidget(self.springID_lineEdit, 1, 2, 1, 1)
        self.name_label = QtGui.QLabel(self.groupBox_basicInfo)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_basicInfo)
        self.groupBox_simulationParameters = QtGui.QGroupBox(Form)
        self.groupBox_simulationParameters.setObjectName(_fromUtf8("groupBox_simulationParameters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_simulationParameters)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bodyIDi_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.bodyIDi_label.setObjectName(_fromUtf8("bodyIDi_label"))
        self.gridLayout_2.addWidget(self.bodyIDi_label, 0, 0, 1, 1)
        self.uPj_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.uPj_label.setObjectName(_fromUtf8("uPj_label"))
        self.gridLayout_2.addWidget(self.uPj_label, 4, 0, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_simulationParameters)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 2)
        self.uPi_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.uPi_label.setObjectName(_fromUtf8("uPi_label"))
        self.gridLayout_2.addWidget(self.uPi_label, 3, 0, 1, 1)
        self.bodyIDj_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.bodyIDj_lineEdit.setObjectName(_fromUtf8("bodyIDj_lineEdit"))
        self.gridLayout_2.addWidget(self.bodyIDj_lineEdit, 1, 1, 1, 1)
        self.bodyIDj_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.bodyIDj_label.setObjectName(_fromUtf8("bodyIDj_label"))
        self.gridLayout_2.addWidget(self.bodyIDj_label, 1, 0, 1, 1)
        self.K_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.K_lineEdit.setObjectName(_fromUtf8("K_lineEdit"))
        self.gridLayout_2.addWidget(self.K_lineEdit, 6, 1, 1, 1)
        self.bodyIDi_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.bodyIDi_lineEdit.setObjectName(_fromUtf8("bodyIDi_lineEdit"))
        self.gridLayout_2.addWidget(self.bodyIDi_lineEdit, 0, 1, 1, 1)
        self.uPi_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.uPi_lineEdit.setObjectName(_fromUtf8("uPi_lineEdit"))
        self.gridLayout_2.addWidget(self.uPi_lineEdit, 3, 1, 1, 1)
        self.K_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.K_label.setObjectName(_fromUtf8("K_label"))
        self.gridLayout_2.addWidget(self.K_label, 6, 0, 1, 1)
        self.D_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.D_label.setObjectName(_fromUtf8("D_label"))
        self.gridLayout_2.addWidget(self.D_label, 7, 0, 1, 1)
        self.uPj_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.uPj_lineEdit.setInputMask(_fromUtf8(""))
        self.uPj_lineEdit.setObjectName(_fromUtf8("uPj_lineEdit"))
        self.gridLayout_2.addWidget(self.uPj_lineEdit, 4, 1, 1, 1)
        self.D_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.D_lineEdit.setObjectName(_fromUtf8("D_lineEdit"))
        self.gridLayout_2.addWidget(self.D_lineEdit, 7, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_simulationParameters)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 5, 0, 1, 2)
        self.L0_lineEdit = QtGui.QLineEdit(self.groupBox_simulationParameters)
        self.L0_lineEdit.setObjectName(_fromUtf8("L0_lineEdit"))
        self.gridLayout_2.addWidget(self.L0_lineEdit, 8, 1, 1, 1)
        self.L0_label = QtGui.QLabel(self.groupBox_simulationParameters)
        self.L0_label.setObjectName(_fromUtf8("L0_label"))
        self.gridLayout_2.addWidget(self.L0_label, 8, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_simulationParameters)
        self.visualization_groupBox = QtGui.QGroupBox(Form)
        self.visualization_groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.visualization_groupBox.setObjectName(_fromUtf8("visualization_groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.visualization_groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scale_lineEdit = QtGui.QLineEdit(self.visualization_groupBox)
        self.scale_lineEdit.setObjectName(_fromUtf8("scale_lineEdit"))
        self.gridLayout_4.addWidget(self.scale_lineEdit, 0, 1, 1, 1)
        self.scale_label = QtGui.QLabel(self.visualization_groupBox)
        self.scale_label.setObjectName(_fromUtf8("scale_label"))
        self.gridLayout_4.addWidget(self.scale_label, 0, 0, 1, 1)
        self.color_lineEdit = QtGui.QLineEdit(self.visualization_groupBox)
        self.color_lineEdit.setObjectName(_fromUtf8("color_lineEdit"))
        self.gridLayout_4.addWidget(self.color_lineEdit, 1, 1, 1, 1)
        self.color_label = QtGui.QLabel(self.visualization_groupBox)
        self.color_label.setObjectName(_fromUtf8("color_label"))
        self.gridLayout_4.addWidget(self.color_label, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.visualization_groupBox)
        self.groupBox_comment = QtGui.QGroupBox(Form)
        self.groupBox_comment.setObjectName(_fromUtf8("groupBox_comment"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_comment)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.comment_textEdit = QtGui.QTextEdit(self.groupBox_comment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_textEdit.sizePolicy().hasHeightForWidth())
        self.comment_textEdit.setSizePolicy(sizePolicy)
        self.comment_textEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.comment_textEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comment_textEdit.setObjectName(_fromUtf8("comment_textEdit"))
        self.gridLayout_3.addWidget(self.comment_textEdit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_comment)
        self.bottom_horizontalLayout = QtGui.QHBoxLayout()
        self.bottom_horizontalLayout.setObjectName(_fromUtf8("bottom_horizontalLayout"))
        self.info_lineEdit = QtGui.QLineEdit(Form)
        self.info_lineEdit.setEnabled(False)
        self.info_lineEdit.setObjectName(_fromUtf8("info_lineEdit"))
        self.bottom_horizontalLayout.addWidget(self.info_lineEdit)
        self.save_pushButton = QtGui.QPushButton(Form)
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.save_pushButton)
        self.cancel_pushButton = QtGui.QPushButton(Form)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.cancel_pushButton)
        self.verticalLayout.addLayout(self.bottom_horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.name_lineEdit, self.springID_lineEdit)
        Form.setTabOrder(self.springID_lineEdit, self.springType_comboBox)
        Form.setTabOrder(self.springType_comboBox, self.bodyIDi_lineEdit)
        Form.setTabOrder(self.bodyIDi_lineEdit, self.bodyIDj_lineEdit)
        Form.setTabOrder(self.bodyIDj_lineEdit, self.uPi_lineEdit)
        Form.setTabOrder(self.uPi_lineEdit, self.uPj_lineEdit)
        Form.setTabOrder(self.uPj_lineEdit, self.K_lineEdit)
        Form.setTabOrder(self.K_lineEdit, self.D_lineEdit)
        Form.setTabOrder(self.D_lineEdit, self.info_lineEdit)
        Form.setTabOrder(self.info_lineEdit, self.save_pushButton)
        Form.setTabOrder(self.save_pushButton, self.cancel_pushButton)
        Form.setTabOrder(self.cancel_pushButton, self.comment_textEdit)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Spring", None))
        self.groupBox_basicInfo.setTitle(_translate("Form", "Basic Info", None))
        self.springID_label.setText(_translate("Form", "Spring id", None))
        self.springType_comboBox.setItemText(0, _translate("Form", "Translational", None))
        self.springType_comboBox.setItemText(1, _translate("Form", "Rotational", None))
        self.springType_label.setText(_translate("Form", "Type", None))
        self.name_label.setText(_translate("Form", "Name", None))
        self.groupBox_simulationParameters.setTitle(_translate("Form", "Simulation Parameters", None))
        self.bodyIDi_label.setText(_translate("Form", "Body ID i", None))
        self.uPj_label.setText(_translate("Form", "u_P i, [x, y]", None))
        self.uPi_label.setText(_translate("Form", "u_P i, [x, y]", None))
        self.bodyIDj_label.setText(_translate("Form", "Body ID j", None))
        self.K_label.setText(_translate("Form", "K, N/m", None))
        self.D_label.setText(_translate("Form", "D, N/m s", None))
        self.L0_label.setText(_translate("Form", "L0, m", None))
        self.visualization_groupBox.setTitle(_translate("Form", "Visualization", None))
        self.scale_label.setText(_translate("Form", "Scale", None))
        self.color_label.setText(_translate("Form", "Color, RGB", None))
        self.groupBox_comment.setTitle(_translate("Form", "Comment", None))
        self.save_pushButton.setText(_translate("Form", "Save", None))
        self.cancel_pushButton.setText(_translate("Form", "Cancel", None))

