# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_widget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(769, 499)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(769, 499))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listWidget = QtGui.QListWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageMain = QtGui.QWidget()
        self.pageMain.setObjectName(_fromUtf8("pageMain"))
        self.gridLayout_3 = QtGui.QGridLayout(self.pageMain)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.pageMain)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.showGCS_checkBox = QtGui.QCheckBox(self.groupBox)
        self.showGCS_checkBox.setObjectName(_fromUtf8("showGCS_checkBox"))
        self.gridLayout_2.addWidget(self.showGCS_checkBox, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageMain)
        self.pageSimulation = QtGui.QWidget()
        self.pageSimulation.setObjectName(_fromUtf8("pageSimulation"))
        self.gridLayout_6 = QtGui.QGridLayout(self.pageSimulation)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 2, 0, 1, 1)
        self.whenSimulationIsFinished_groupBox = QtGui.QGroupBox(self.pageSimulation)
        self.whenSimulationIsFinished_groupBox.setObjectName(_fromUtf8("whenSimulationIsFinished_groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.whenSimulationIsFinished_groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.loadSolutionFileStatus_2 = QtGui.QCheckBox(self.whenSimulationIsFinished_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSolutionFileStatus_2.sizePolicy().hasHeightForWidth())
        self.loadSolutionFileStatus_2.setSizePolicy(sizePolicy)
        self.loadSolutionFileStatus_2.setMinimumSize(QtCore.QSize(200, 0))
        self.loadSolutionFileStatus_2.setObjectName(_fromUtf8("loadSolutionFileStatus_2"))
        self.gridLayout_4.addWidget(self.loadSolutionFileStatus_2, 0, 0, 1, 1)
        self.loadSolutionFileStatus = QtGui.QCheckBox(self.whenSimulationIsFinished_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSolutionFileStatus.sizePolicy().hasHeightForWidth())
        self.loadSolutionFileStatus.setSizePolicy(sizePolicy)
        self.loadSolutionFileStatus.setMinimumSize(QtCore.QSize(200, 0))
        self.loadSolutionFileStatus.setObjectName(_fromUtf8("loadSolutionFileStatus"))
        self.gridLayout_4.addWidget(self.loadSolutionFileStatus, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.whenSimulationIsFinished_groupBox, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 1, 1, 1)
        self.displayUpdate_groupBox = QtGui.QGroupBox(self.pageSimulation)
        self.displayUpdate_groupBox.setObjectName(_fromUtf8("displayUpdate_groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.displayUpdate_groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.dt_lineEdit = QtGui.QLineEdit(self.displayUpdate_groupBox)
        self.dt_lineEdit.setObjectName(_fromUtf8("dt_lineEdit"))
        self.gridLayout_8.addWidget(self.dt_lineEdit, 3, 2, 1, 1)
        self.updateDisplay_label = QtGui.QLabel(self.displayUpdate_groupBox)
        self.updateDisplay_label.setObjectName(_fromUtf8("updateDisplay_label"))
        self.gridLayout_8.addWidget(self.updateDisplay_label, 0, 0, 1, 1)
        self.steps_lineEdit = QtGui.QLineEdit(self.displayUpdate_groupBox)
        self.steps_lineEdit.setObjectName(_fromUtf8("steps_lineEdit"))
        self.gridLayout_8.addWidget(self.steps_lineEdit, 2, 2, 1, 1)
        self.updateDisplay_comboBox = QtGui.QComboBox(self.displayUpdate_groupBox)
        self.updateDisplay_comboBox.setObjectName(_fromUtf8("updateDisplay_comboBox"))
        self.updateDisplay_comboBox.addItem(_fromUtf8(""))
        self.updateDisplay_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.updateDisplay_comboBox, 0, 2, 1, 1)
        self.dt_label = QtGui.QLabel(self.displayUpdate_groupBox)
        self.dt_label.setObjectName(_fromUtf8("dt_label"))
        self.gridLayout_8.addWidget(self.dt_label, 2, 0, 1, 1)
        self.steps_label = QtGui.QLabel(self.displayUpdate_groupBox)
        self.steps_label.setObjectName(_fromUtf8("steps_label"))
        self.gridLayout_8.addWidget(self.steps_label, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.displayUpdate_groupBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageSimulation)
        self.pageVisualization = QtGui.QWidget()
        self.pageVisualization.setObjectName(_fromUtf8("pageVisualization"))
        self.gridLayout_7 = QtGui.QGridLayout(self.pageVisualization)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.pageVisualization)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.infoDisplay_groupBox = QtGui.QGroupBox(self.pageVisualization)
        self.infoDisplay_groupBox.setObjectName(_fromUtf8("infoDisplay_groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.infoDisplay_groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.filename_checkBox = QtGui.QCheckBox(self.infoDisplay_groupBox)
        self.filename_checkBox.setObjectName(_fromUtf8("filename_checkBox"))
        self.verticalLayout.addWidget(self.filename_checkBox)
        self.simulationTime_checkBox = QtGui.QCheckBox(self.infoDisplay_groupBox)
        self.simulationTime_checkBox.setObjectName(_fromUtf8("simulationTime_checkBox"))
        self.verticalLayout.addWidget(self.simulationTime_checkBox)
        self.simulationStepNumber_checkBox = QtGui.QCheckBox(self.infoDisplay_groupBox)
        self.simulationStepNumber_checkBox.setObjectName(_fromUtf8("simulationStepNumber_checkBox"))
        self.verticalLayout.addWidget(self.simulationStepNumber_checkBox)
        self.timeAndDate_checkBox = QtGui.QCheckBox(self.infoDisplay_groupBox)
        self.timeAndDate_checkBox.setObjectName(_fromUtf8("timeAndDate_checkBox"))
        self.verticalLayout.addWidget(self.timeAndDate_checkBox)
        self.gridLayout_7.addWidget(self.infoDisplay_groupBox, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 2, 1, 1, 1)
        self.visualization_groupBox = QtGui.QGroupBox(self.pageVisualization)
        self.visualization_groupBox.setObjectName(_fromUtf8("visualization_groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.visualization_groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.editBackgroundColor_pushButton = QtGui.QPushButton(self.visualization_groupBox)
        self.editBackgroundColor_pushButton.setObjectName(_fromUtf8("editBackgroundColor_pushButton"))
        self.gridLayout_5.addWidget(self.editBackgroundColor_pushButton, 0, 2, 1, 1)
        self.backgroundColor_lineEdit = QtGui.QLineEdit(self.visualization_groupBox)
        self.backgroundColor_lineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.backgroundColor_lineEdit.setObjectName(_fromUtf8("backgroundColor_lineEdit"))
        self.gridLayout_5.addWidget(self.backgroundColor_lineEdit, 0, 1, 1, 1)
        self.updateDisplayStep = QtGui.QLineEdit(self.visualization_groupBox)
        self.updateDisplayStep.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.updateDisplayStep.setObjectName(_fromUtf8("updateDisplayStep"))
        self.gridLayout_5.addWidget(self.updateDisplayStep, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.visualization_groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.updateDisplayStepLabel = QtGui.QLabel(self.visualization_groupBox)
        self.updateDisplayStepLabel.setObjectName(_fromUtf8("updateDisplayStepLabel"))
        self.gridLayout_5.addWidget(self.updateDisplayStepLabel, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 2, 3, 1, 1)
        self.gridLayout_7.addWidget(self.visualization_groupBox, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.pageVisualization)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Preferences", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "Main", None))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "Simulation", None))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "Visualization", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("Form", "Main", None))
        self.showGCS_checkBox.setText(_translate("Form", "Show GCS", None))
        self.whenSimulationIsFinished_groupBox.setTitle(_translate("Form", "When simulation is finished", None))
        self.loadSolutionFileStatus_2.setText(_translate("Form", "Restore initial conditions", None))
        self.loadSolutionFileStatus.setText(_translate("Form", "Load solution", None))
        self.displayUpdate_groupBox.setTitle(_translate("Form", "Display update", None))
        self.updateDisplay_label.setText(_translate("Form", "During simulation update display on every", None))
        self.updateDisplay_comboBox.setItemText(0, _translate("Form", "dt", None))
        self.updateDisplay_comboBox.setItemText(1, _translate("Form", "step", None))
        self.dt_label.setText(_translate("Form", "dt", None))
        self.steps_label.setText(_translate("Form", "steps", None))
        self.label.setText(_translate("Form", "Visualization", None))
        self.infoDisplay_groupBox.setTitle(_translate("Form", "Info display", None))
        self.filename_checkBox.setText(_translate("Form", "Filename", None))
        self.simulationTime_checkBox.setText(_translate("Form", "Simulation time", None))
        self.simulationStepNumber_checkBox.setText(_translate("Form", "Step number", None))
        self.timeAndDate_checkBox.setText(_translate("Form", "Time and date", None))
        self.visualization_groupBox.setTitle(_translate("Form", "Open GL", None))
        self.editBackgroundColor_pushButton.setText(_translate("Form", "Edit", None))
        self.label_3.setText(_translate("Form", "Background color", None))
        self.updateDisplayStepLabel.setText(_translate("Form", "Update display on i-th stp", None))

